
sandbox:
  enabled: true

# make sure you enable introspection
supergraph:
  introspection: true

# make sure homepage is disabled
homepage:
  enabled: false

traffic_shaping:
  deduplicate_variables: true # Enable the variable deduplication optimization.
  all:
    deduplicate_query: true # Enable query deduplication for all subgraphs.